### ISSUE TITLE
More useful tags

### ISSUE THREAD

**Issue by beihaifeiwu** [theborakompanioni/thymeleaf-extras-shiro#10]
I think you can add more useful tags to the thymeleaf shiro extensions like

![image](https://cloud.githubusercontent.com/assets/5372382/7291296/cd772208-e9c0-11e4-8b0e-8b4ff995683c.png)

Almost in every project used shiro, I have to create them. It will be wonderful you can add them to the
extensions!

**Comment by theborakompanioni** [comment]
Sorry it took so long for an answer. Your suggestions will be implemented.

**Comment by theborakompanioni** [comment]
added `hasAnyPermissions`, `hasAllPermissions` and `hasAllRoles` in v1.2.0

**Comment by theborakompanioni** [comment]
It seems there was a problem with uploading v1.2.0 to maven central. Please use v1.2.1.
