### ISSUE TITLE
how cant i set principal's property to input value?

### ISSUE THREAD

**Issue by heshunwq** [theborakompanioni/thymeleaf-extras-shiro#12]
some code like this:
<code> input type="hidden" name="username" th:value="${ shiro:principal property="username"/}"/"</code>
of course it don't work，but how can i do?

**Comment by theborakompanioni** [comment]
Sorry for the late reply. You will have to put the principal into the thymeleaf context for yourself.
e.g.
```
WebContext ctx = new WebContext(request, servletContext, request.getLocale());
ctx.setVariable("principal",  org.apache.shiro.SecurityUtils.getSubject().getPrincipal());

templateEngine.process("myTemplate", ctx, response.getWriter());
```
