### ISSUE TITLE
shiro:user tag seems to be ignored

### ISSUE THREAD

**Issue by saviola777** [theborakompanioni/thymeleaf-extras-shiro#15]
Hello,

I recently updated to version `2.0.0` (and I updated my dependencies Thymeleaf to version `3.0.2.RELEASE` and Shiro to version `1.3.2` along with it).

I tried all of

```
<th:block shiro:user>
<th:block shiro:user="">
<shiro:user>
```

but in each case, the code is executed despite the user not being logged in. I have added

```
xmlns:shiro="http://www.pollix.at/thymeleaf/shiro"
```

in both the main template and the fragment where the shiro tags are used (but Thymeleaf doesn't report any errors, so the code seems to be parsing fine).

The following code still works:

```
<th:block th:if="${T(at.pollux.thymeleaf.shiro.processor.ShiroFacade).isUser()}">
```

What am I doing wrong, and what further information could I provide to help you track down the source of the issue? Thanks in advance.

PS: Sorry for the bad issue title, feel free to rename it.

**Comment by theborakompanioni** [comment]
@saviola777 Thank you for reporting. Seems odd. The UserElementProcesser is very simple and internally uses `ShiroFacade.isUser()`. .Does the same happen with a simple `<div>`?  Is the same true for "shiro:guest"? Do you use any other dialect? Has the user been previously logged in ("remember me", cache cleaned, etc.)?

It might be the case that the element is rendered when the user is "remembered" but not actually authenticated. But then `T(at.pollux.thymeleaf.shiro.processor.ShiroFacade).isUser()` would produce the same results... first guess would be that it has something to do with the "th:block".

I just quickly tried to reproduce it without luck (see 7fb0ed30d6) and will take a deeper look into it in the coming days. Thank you, fine sir, for your help.

**Comment by saviola777** [comment]
Ah, so sorry, I'm an idiot! (The "my screen isn't working!"-"is it plugged in?"-"of course, how stupid do you think... oh wait it isn't." kind of idiot) It's working perfectly now, sorry for wasting your time (out of embarrassment, I will not share the exact mistake I made unless you insist).

**Comment by theborakompanioni** [comment]
@saviola777 I make mistakes all the time - it's a great way to learn. :-) So do not be too judgemental with yourself. Please keep reporting issues or any other misbehaviour - you are not wasting my time. In fact, it is the other way around: You are putting in effort and spending time. This library profits from your work! Thank you!
