### ISSUE TITLE
Shrio Tags not working

### ISSUE THREAD

**Issue by ydalley** [theborakompanioni/thymeleaf-extras-shiro#16]
All the shrio tags don't seem to work. 

I'm using the thymeleaf layout dialect and the shiro dialect.

`<th:block th:if="${T(at.pollux.thymeleaf.shiro.processor.ShiroFacade).isUser()}">` works

I checked this [issue](https://github.com/theborakompanioni/thymeleaf-extras-shiro/issues/15) and I wish @saviola777 shared what his final solution or mistake was.

I really don't want to use the `th:if `syntax.

Help!

**Comment by saviola777** [comment]
I forgot to add the `ShiroDialect` to the template engine, e.g.

```
@Bean
@Autowired
public SpringTemplateEngine templateEngine(ITemplateResolver templateResolver) {
	SpringTemplateEngine engine = new SpringTemplateEngine();
	engine.setTemplateResolver(templateResolver);
	// Enable shiro dialect for thymeleaf
	engine.addDialect(new ShiroDialect());
	return engine;
}
```

in a `@Configuration` class.

**Comment by ydalley** [comment]
Looks like i did the same thing, I didn't have to add the other dialects . I completely forgot!
Thanks!
