### ISSUE TITLE
  pollux.thymeleaf.shiro.dialect.ShiroDialect class not found

### ISSUE THREAD

**Issue by weilei379909499** [theborakompanioni/thymeleaf-extras-shiro#23]
when I using springboot2.0 the class ShiroDialect not found

**Comment by ShadowDAssange** [comment]
<property name="additionalDialects">
            <set>
                <bean class="at.pollux.thymeleaf.shiro.dialect.ShiroDialect"/>
            </set>
        </property>

I have error

**Comment by ShadowDAssange** [comment]
<property name="additionalDialects">
            <set>
                <bean class="at.pollux.thymeleaf.shiro.dialect.ShiroDialect"/>
            </set>
        </property>

**Comment by ShadowDAssange** [comment]
same error in spring-mvc.xml
